# Generated by Django 5.2.4 on 2025-08-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created Password'), ('update', 'Updated Password'), ('delete', 'Deleted Password'), ('audit', 'Performed Audit'), ('login', 'User Login'), ('logout', 'User Logout')], max_length=20),
        ),
    ]
